apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui-service
  namespace: argocd
spec:
  project: workloads
  sources:
    - repoURL: https://github.com/Ingress-Q/ui-service.git
      targetRevision: main
      path: ui-service
      helm:
        valueFiles:
          - $values/environments/dev/ui-service-values.yaml
    - repoURL: https://github.com/Ingress-Q/gitops-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true