apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: api-keys

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: api-keys

  data:
    - secretKey: STRIPE_API_KEY
      remoteRef:
        key: dev/api-keys
        property: stripe

    - secretKey: SENDGRID_API_KEY
      remoteRef:
        key: dev/api-keys
        property: sendgrid