apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: cart-db
  namespace: cart

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: cart-db

  data:
    - secretKey: username
      remoteRef:
        key: dev/cart-db
        property: username

    - secretKey: password
      remoteRef:
        key: dev/cart-db
        property: password