apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: catalog-db
  namespace: catalog

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: catalog-db

  data:
    - secretKey: username
      remoteRef:
        key: dev/catalog-db
        property: username

    - secretKey: password
      remoteRef:
        key: dev/catalog-db
        property: password