apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: jwt-secret

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: jwt-secret

  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: dev/jwt
        property: secret