apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: orders-db
  namespace: orders

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: orders-db

  data:
    - secretKey: username
      remoteRef:
        key: dev/orders-db
        property: username

    - secretKey: password
      remoteRef:
        key: dev/orders-db
        property: password