apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
spec:
  description: Business applications

  sourceRepos:
    - '*'

  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: stage
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc
