apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd

spec:
  description: Retail workloads

  sourceRepos:
    - '*'

  destinations:
    - namespace: catalog
      server: https://kubernetes.default.svc

    - namespace: cart
      server: https://kubernetes.default.svc

    - namespace: checkout
      server: https://kubernetes.default.svc

    - namespace: orders
      server: https://kubernetes.default.svc

    - namespace: ui
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'