apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: security
  namespace: argocd

spec:
  project: platform

  source:
    repoURL: https://github.com/Ingress-Q/gitops-platform.git
    targetRevision: main
    path: applications/platform/security

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true