apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service-dev
  namespace: argocd
spec:
  project: workloads

  source:
    repoURL: https://github.com/Ingress-Q/user-service.git
    targetRevision: main
    path: helm

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      selfHeal: true
