apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: external-dns
  namespace: argocd

spec:
  project: platform

  source:
    repoURL: https://kubernetes.github.io/external-dns
    chart: external-dns
    targetRevision: 4.13.2

  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true