apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checkout-service
  namespace: argocd
spec:
  project: workloads
  sources:
    - repoURL: https://github.com/Ingress-Q/checkout-service.git
      targetRevision: main
      path: checkout-service
      helm:
        valueFiles:
          - $values/environments/dev/checkout-service-values.yaml
    - repoURL: https://github.com/Ingress-Q/gitops-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: checkout
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true