replicaCount: 2

image:
  repository: 709476087242.dkr.ecr.us-east-1.amazonaws.com/checkout-service
  tag: 48f4580a818d31e59ae5fcb3a45e5e0324af8d8a

environment: dev

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 1

serviceAccount:
  create: true
  name: checkout-service

observability:
  logging:
    level: DEBUG

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: retail-store
  host: ""  # no custom domain — ALB DNS name auto-assigned, leave host unset for path-based routing
  path: /checkout