replicaCount: 2

image:
  repository: 709476087242.dkr.ecr.us-east-1.amazonaws.com/ui-service
  tag: 89a7ce1a97ccf60d35c12aa93b21fa24b1a58dad

environment: dev

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 1

serviceAccount:
  create: true
  name: ui-service

observability:
  logging:
    level: DEBUG